"""
Django settings for enbedingbot project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("DJANGO_SECRET_KEY", default="django-insecure-placeholder")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = [
    host.strip()
    for host in env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'pgvector.django',
    'ingestion',
    'bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("LOCAL_DB_NAME"),
        'USER': env("LOCAL_DB_USER"),
        'PASSWORD': env("LOCAL_DB_PASSWORD"),
        'HOST': env("LOCAL_DB_HOST", default="localhost"),
        'PORT': env("LOCAL_DB_PORT", default="5432"),
        'TEST': {
            'NAME': 'test_embedding_local_db',
            'TEMPLATE': 'template0',
        },
    },
    'vectors': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("VECTOR_DB_NAME"),
        'USER': env("VECTOR_DB_USER"),
        'PASSWORD': env("VECTOR_DB_PASSWORD"),
        'HOST': env("VECTOR_DB_HOST"),
        'PORT': env("VECTOR_DB_PORT", default="5432"),
        'TEST': {
            'MIRROR': 'default',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TELEGRAM_TOKEN = env("TELEGRAM_TOKEN", default="")
MISTRAL_API_KEY = env("MISTRAL_API_KEY", default="")

DATABASE_ROUTERS = ['ingestion.db_router.EmbeddingRouter']
